### PR TITLE
Updates | lambda.rb

### PR DESCRIPTION
**Pull request by Nebula-Ninjas**
@joshlarsen added the following:

Lines 17 - 27, 176 - 181
Lines 29 - 40, 183 - 204

The just need to be reviewed and see if I did it correctly. Once I updated the `lambda.rb` file with these changes I was able to load the custom data without getting any of the following errors:

`worker_1  | Loader job failed - NoMethodError undefined method `vpc_id' for #<String:0x00007fee9146fca8> (/app/app/jobs/lib/loader/asset/loaders/aws_loader/lambda.rb:21:in `function')
worker_1  | Runner job failed - NoMethodError undefined method `vpc_id' for #<String:0x00007fee9146fca8> (/app/app/jobs/lib/loader/asset/loaders/aws_loader/lambda.rb:21:in `function')`

Hope I did it correctly.

Also, while on the Lambda topic am I supposed to be seeing the service within the OpenCSPM web page?

Hope you have a great weekend!

William

### CODE REVIEW

**Comment by joshlarsen** [comment]
@Nebula-Ninjas I pulled this over into it's own branch to take a look.

There are a few issues:

We don't need

```ruby
def vpc
...
end
```

and

```ruby
def subnet
...
end
```

here because those entities don't appear in the Lambda function resource JSON, only the EC2 resources. They'll get loaded/upserted by the EC2 loader.

The other issue is that in my testing, I see the VPC info under the `vpc_config` key, not just `vpc_id`. For example:

```json
{
  "account": "1234567890123",
  "service": "Lambda",
  "region": "us-east-1",
  "resource": {
    "function_name": "lambda-vpc-test",
    "function_arn": "arn:aws:lambda:us-east-1:1234567890123:function:lambda-vpc-test",
    "runtime": "nodejs12.x",
    "role": "arn:aws:iam::1234567890123:role/service-role/lambda-vpc-test",
    "handler": "index.handler",
    "code_size": 856,
    "description": "A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.",
    "timeout": 10,
    "memory_size": 512,
    "last_modified": "2021-04-25 20:48:53 +0000",
    "code_sha_256": "E4HWnUFtLDweNO950YRTEYkjq3MzA7B3BnGrSPUX5R4=",
    "version": "$LATEST",
    "vpc_config": {
      "subnet_ids": ["subnet-96171dca", "subnet-f9c811b4", "subnet-e6673ad8"],
      "security_group_ids": ["sg-29254f7d"],
      "vpc_id": "vpc-b1c993cb"
    },
    "dead_letter_config": null,
    "environment": null,
    "kms_key_arn": null,
    "tracing_config": {
      "mode": "PassThrough"
    },
    "master_arn": null,
    "revision_id": "c71c70f9-eed7-4fad-bf4b-621102abe45a",
    "layers": [],
    "state": null,
    "state_reason": null,
    "state_reason_code": null,
    "last_update_status": null,
    "last_update_status_reason": null,
    "last_update_status_reason_code": null,
    "file_system_configs": null,
    "package_type": "Zip",
    "image_config_response": null,
    "signing_profile_version_arn": null,
    "signing_job_arn": null,
    "type": "function",
    "arn": "arn:aws:lambda:us-east-1:1234567890123:function:lambda-vpc-test",
    "policy": {
      "Version": "2012-10-17",
      "Id": "default",
      "Statement": [
        {
          "Sid": "lambda-94fcc308-cead-4b12-91da-452d853c819c",
          "Effect": "Allow",
          "Principal": {
            "Service": "apigateway.amazonaws.com"
          },
          "Action": "lambda:InvokeFunction",
          "Resource": "arn:aws:lambda:us-east-1:1234567890123:function:lambda-vpc-test",
          "Condition": {
            "ArnLike": {
              "AWS:SourceArn": "arn:aws:execute-api:us-east-1:1234567890123:vhv5dd1tj2/*/*/lambda-vpc-test"
            }
          }
        }
      ]
    }
  },
  "timestamp": "2021-05-28 21:29:46 UTC"
}

```

so the key is going to be `@data.vpc_config.vpc_id` if the Lambda is in a VPC. Can you confirm your Lambda JSON is in the same shape as above? (e.g. via `cat output.json | grep '"service":"Lambda"' | jq`)

**Comment by Nebula-Ninjas** [comment]
@joshlarsen thank you for taking a look at this. I'll admit that I do not know a great deal on coding, just good at comparing other code and seeing what was done and seeing if it would remedy the issue I was having.

To answer your question, I believe the differences I am seeing is how the JSON file outputted the the `vpc_config` portion.

My Example:

`"vpc_config": "{:subnet_ids=>[\"subnet-0f82efdd701104eb8\", \"subnet-011e9efc9b2413686\", \"subnet-061f5099abf30db87\", \"subnet-0997b20811fe72aa2\"], :security_group_ids=>[\"sg-07654186633011770\"], :vpc_id=>\"vpc-0708c1f757a3cef40\"}",`

For some reason mine has `\` and `>` on the functions with an association with a VPC. Additionally, I have a `"dead_letter_config"`, `"environment"`, and `"tracing_config"' that all seem to have the same thing.

Lastly, my `"vpc_config"`, `"dead_letter_config"`, and `"environment"` didn't format the JSON as yours with line breaks after the commas.

Based on your example and mine, I suspect it is the `\` and `>` that could be the culprit. What do you think?

Nonetheless, I'll see if I have some time today to edit the JSON for those oddities and test.

Thanks in advanced!

Sincerely,

William

**Comment by joshlarsen** [comment]
@Nebula-Ninjas ah, it looks like you're using an older version of `aws_recon`. Better parsing of the `vpc_config` was added in a recent [update](https://github.com/darkbitio/aws-recon/commit/4faeaa2364cdb9706a4fbac3d3c339fd7636968f?branch=4faeaa2364cdb9706a4fbac3d3c339fd7636968f&diff=split). Can you please ensure you have the latest AWS Recon and re-run your collection?

**Comment by Nebula-Ninjas** [comment]
@joshlarsen I pulled/used the Docker image and it is running `0.5.3`. Do you know when/if this image will be updated soon?

`AWS Recon - AWS Inventory Collector (0.5.3)`

Sincerely,

William

**Comment by joshlarsen** [comment]
@Nebula-Ninjas the latest is `0.5.11`. To re-pull:

```
docker pull darkbitio/aws_recon:latest
```

**Comment by Nebula-Ninjas** [comment]
@joshlarsen re-pulled the latest, re-ran aws-recon and that fixed the lambda section.

Additionally, I deleted and re-pulled the OpenCSPM project and tested with the JSON file and it loaded with no errors.

What I am finding is that I can not see anything `pass/fail` related to Lambda within the console, is this the expected behavior?

William

**Comment by joshlarsen** [comment]
@Nebula-Ninjas so far, all of the controls related to Lambda are in the Enterprise control pack.

**Pull request merged**
